channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - nomkl
  - python
  # - importlib-metadata   # [py<38]
  - ruamel.yaml
  - snakemake-minimal >= 7.22.0
  - samtools >=1.13
  - cutadapt >=5.1
  - bowtie2 >=2.5.4
  - strobealign >= 0.13.0
  - je-suite >=2.0.RC
  - deeptools >=3.5.0
  - picard >=3.4.0
  - fastqc >=0.11.9
  - bedtools >=2.30.0
  - multiqc >1.20
  - xopen >=1.2.0
  - sra-tools >=2.11.0
  - r-base >=4.0.0
  - r-ggplot2 >=3.3.0
  - r-dplyr >=1.0.0
  # click 8.2.2 release crashes MultiQC 1.30
  - click =8.2.1
